config/routes.rb
Rails.application.routes.draw do

 resources :folders
 resources :uploads
 devise_for :users
 root :to => "home#index"
 match "uploads/get/:id" => "uploads#get", :as => "download", via: [:get]
 match "browse/:folder_id" => "home#browse", :as => "browse", via: [:get, :post]
 match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder" , via: [:get,:post]
 match "browse/:folder_id/new_file" => "uploads#new", :as => "new_sub_file" , via: [:get,:post]
 match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder", via: [:get,:post]
 match "home/share" => "home#share", via: [:get,:post]
 match ":browse/:id/share/delete" => "uploads#bulk_delete", via: [:get,:post]
 match ":browse/home/label_search" => "uploads#label_search", via: [:get,:post]
 match "/home/label_search" => "uploads#label_search", via: [:get,:post]
 match "home/activity_data" => "home#activity_data",:as => "activity", via: [:get,:post]
 # match "/home/activity_data" => "home#activity_data",:as => "activity", via: [:get,:post]

 resources :uploads do
    resources :comments
  end

  resources 'surveys'
  resources 'attempts'
  delete 'attempts/:survey_id/:user_id' => 'attempts#delete_user_attempts', as: :delete_user_attempts
  post 'user/:id/change_name' => 'users#change_name', as: :change_user_name

  
  resources :comments do
    resources :comments
  end
end

app/models/folder.rb
class Folder < ApplicationRecord
  acts_as_tree
  belongs_to :user
  has_many :uploads, :dependent => :destroy
  has_many :shared_folders, :dependent => :destroy

  audited associated_with: :user

  def shared?
    !self.shared_folders.empty?
  end

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_folder, only: [:show, :update, :destroy]
  # before_action :chk_folder_id, only: [ :new]

  # GET /folders
  # GET /folders.json
  def index
    @folders = current_user.folders
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = current_user.folders.find(params[:id])
  end

  # GET /folders/new
  def new
    @folder = current_user.folders.new
    if params[:folder_id]
      @current_folder = current_user.folders.find(params[:folder_id])
      @folder.parent_id = @current_folder.id
    end
  end

  def edit
    @folder = current_user.folders.find(params[:folder_id])
    @current_folder = @folder.parent
  end


  def create
    @folder = current_user.folders.new(folder_params)
    if @folder.save
      flash[:notice] = "Successfully created folder."

      if @folder.parent
        redirect_to browse_path(@folder.parent)
      else
        redirect_to root_url
      end
    else
      render :action => 'new'
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    @folder = current_user.folders.find(params[:id])
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @folder = current_user.folders.find(params[:id])
    @parent_folder = @folder.parent #grabbing the parent folder
    @folder.destroy
    flash[:notice] = "Successfully deleted the folder and all the contents inside."
    if @parent_folder
      redirect_to browse_path(@parent_folder)
    else
      redirect_to root_url
    end
  end

  private
  def set_folder
    @folder = Folder.find(params[:id])
  end

  def folder_params
    params.require(:folder).permit(:name, :parent_id, :user_id)
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.hidden_field :parent_id %>
  </p>

  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>  -->

  <p>
    <% if @folder.new_record? %>
      <%= f.submit "Create Folder" %>
    <% else %>
      <%= f.submit "Rename Folder" %>
    <% end %>
  </p>

<% end %>

app/views/folders/edit.html.erb
<%="Rename Folder" %> 
<%= render :partial => "home/breadcrumbs" %>

<%= render 'form' %>

<p>
<% if @folder.parent %>
   <%= link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent) %>
<% else %>
   <%= link_to "Back", root_url %>
<% end %>
</p>

app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= folder.parent_id %></td>
        <td><%= folder.user_id %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New Folder</h1>
<%= render :partial => "home/breadcrumbs" %>

<%= render 'form', folder: @folder %>
<p>
<% if @folder.parent %>
   <%= link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent) %>
<% else %>
   <%= link_to "Back to Home page", root_url %>
<% end %>
</p>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @folder.parent_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @folder.user_id %>
</p>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>