config/routes.rb
Rails.application.routes.draw do

 resources :folders
 resources :uploads
 devise_for :users
 root :to => "home#index"
 match "uploads/get/:id" => "uploads#get", :as => "download", via: [:get]
 match "browse/:folder_id" => "home#browse", :as => "browse", via: [:get, :post]
 match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder" , via: [:get,:post]
 match "browse/:folder_id/new_file" => "uploads#new", :as => "new_sub_file" , via: [:get,:post]
 match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder", via: [:get,:post]
 match "home/share" => "home#share", via: [:get,:post]
 match ":browse/:id/share/delete" => "uploads#bulk_delete", via: [:get,:post]
 match ":browse/home/label_search" => "uploads#label_search", via: [:get,:post]
 match "/home/label_search" => "uploads#label_search", via: [:get,:post]
 match "home/activity_data" => "home#activity_data",:as => "activity", via: [:get,:post]
 # match "/home/activity_data" => "home#activity_data",:as => "activity", via: [:get,:post]

 resources :uploads do
    resources :comments
  end

  resources 'surveys'
  resources 'attempts'
  delete 'attempts/:survey_id/:user_id' => 'attempts#delete_user_attempts', as: :delete_user_attempts
  post 'user/:id/change_name' => 'users#change_name', as: :change_user_name

  
  resources :comments do
    resources :comments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @being_shared_folders = current_user.shared_folders_by_others
      @folders = current_user.folders.roots
      @uploads_label = current_user.uploads.map(&:label).uniq
      @uploads = current_user.uploads.where("folder_id is NULL").order("uploaded_file_file_name desc")
    end
  end

  def browse
    @current_folder = current_user.folders.find_by_id(params[:folder_id])
    @is_this_folder_being_shared = false if @current_folder
    @uploads_label = current_user.uploads.map(&:label).uniq
    if @current_folder.nil?
      folder = Folder.find_by_id(params[:folder_id])

      @current_folder ||= folder if current_user.has_share_access?(folder)
      @is_this_folder_being_shared = true if @current_folder

    end
    if @current_folder
      @being_shared_folders = []
      @folders = @current_folder.children
      @uploads = current_user.uploads.where("folder_id = #{@current_folder.id}").order("uploaded_file_file_name desc")
      render :action => "index"
    else
      flash[:error] = "Don't be cheeky! Mind your own folders!"
      redirect_to root_url
    end
   end



def share
    email_addresses = params[:email_addresses].split(",")

    email_addresses.each do |email_address|
      @shared_folder = current_user.shared_folders.new
      @shared_folder.folder_id = params[:folder_id]
      @shared_folder.shared_email = email_address
      shared_user = User.find_by_email(email_address)
      @shared_folder.shared_user_id = shared_user.id if shared_user
      @shared_folder.message = params[:message]
      @shared_folder.save
      UserMailer.invitation_to_share(@shared_folder).deliver
    end
    respond_to do |format|
      format.js {
      }
    end
end

def activity_data
  from_date = Date.today - 7
  uploads_id = (current_user.uploads.where("created_at >= ?", from_date)).map &(:id)
  @upload_audited_data1 = Audited.audit_class.where("associated_id  IN ('#{uploads_id.join("','")}') AND associated_type = 'Upload' AND auditable_type = 'Comment'")
  @upload_audited_data2 = current_user.associated_audits.where("created_at >= ?", from_date)
end

end

app/views/home/_breadcrumbs.html.erb
<div class="breadcrumbs">
    <% if @current_folder #checking if we are under any folder %>
        <%= link_to "ShareBox", root_url %>
        <% @current_folder.ancestors.reverse.each do |folder| %>
            » <%= link_to folder.name, browse_path(folder) %>
        <% end %>
         »  <%= @current_folder.name %>
    <% else %>
        ShareBox
    <% end %>
</div>

app/views/home/_search_label.html.erb
<div>
  <br>
  <%=label_tag 'Label Search'%>
  <br>
  <%= form_tag 'home/label_search' do%>
    <% @uploads_label.each do |label| %>
      <% if !label.nil? %>
        <%= check_box_tag "label_names[]", "#{label}" %>
        <%= label_tag "#{label}"%>
      <%end%>
    <% end %>
    <%= submit_tag 'Search'%>
  <% end%>
</div>
<br>

app/views/home/activity_data.html.erb
<%= "Recent Activity for last 7 days"%>
<br>
<% if @upload_audited_data1.present? %>
<br>
<% @upload_audited_data1.each do |audit| %>
<%user = (User.find_by_id(audit.user_id)).email%>
<%if audit.action == 'create'%>
  <%="#{user} has created #{audit.auditable_type} with "%>
  <% audit.audited_changes.each do |key,val| %>
    <%= " #{key} as #{val} "%>
    <br>
  <% end %>
<%elsif audit.action == 'update'%>
<br>
  <%="#{user} has updated #{audit.auditable_type} with "%>
  <% audit.audited_changes.each do |key,val| %>
    <% if val[0].blank? %>
      <%= "#{key} changed from blank to #{val[1]}"%>
    <%else%>
      <%= "#{key} changed from #{val[0]} to #{val[1]}"%>
    <%end%>
  <% end %>
  <br>
<%else%>
<br>
  <%name_data = ((audit.auditable_type.constantize).find_by_id(audit.auditable_id.to_i)).try(:name)%>
  <%="#{user} has deleted #{audit.auditable_type} with id = #{audit.auditable_id} and name as #{name_data}"%>
  <br>
<%end%>
<% end %>
<%end%>


<% if @upload_audited_data2.present? %>
<% @upload_audited_data2.each do |audit| %>
<%user = (User.find_by_id(audit.user_id)).email%>
<%if audit.action == 'create'%>
<br>
  <%="#{user} has created #{audit.auditable_type} with "%>
  <% audit.audited_changes.each do |key,val| %>
    <%= " #{key} as #{val} "%>
    <br>
  <% end %>

<%elsif audit.action == 'update'%>
<br>
  <%="#{user} has updated #{audit.auditable_type} with "%>
  <% audit.audited_changes.each do |key,val| %>
    <% if val[0].blank? %>
      <%= "#{key} changed from blank to #{val[1]}"%>
    <%else%>
      <%= "#{key} changed from #{val[0]} to #{val[1]}"%>
    <%end%>
  <% end %>
  <br>
<%else%>
<br>
  <%name_data = ((audit.auditable_type.constantize).find_by_id(audit.auditable_id.to_i)).try(:name)%>
  <%="#{user} has deleted #{audit.auditable_type} with id = #{audit.auditable_id} and name as #{name_data}"%>
  <br>
<%end%>
<% end %>
<%end%>

app/views/home/index.html.erb
<% unless user_signed_in? %>
<div class="jumbotron">
  <h2>
    Upload....Connect....Share...HAVE FUN !!
  </h2>
  <p>
    This is for uploading your files, sharing them with other users registered with our site. Also, go through our questionner!
  </p>
  <p>
    <%=link_to "Sign-in", user_session_path%>
    <%=link_to "/ Sign-up", new_user_registration_path%>
  </p>
</div>
<% else %>
<div id="menu">
  <% unless @is_this_folder_being_shared %>
      <ul id= "top_menu">
          <% if @current_folder %>
              <li><%= link_to "Upload", new_sub_file_path(@current_folder) %></li>
              <li><%= link_to "New Folder", new_sub_folder_path(@current_folder) %></li>
          <% else %>
              <li><%= link_to "Upload", new_upload_path %></li>
              <li><%= link_to "New Folder", new_folder_path %></li>
          <% end %>
      </ul>
  <% else %>
      <h3>This folder is being shared to you by <%= @current_folder.user.email %></h3>
  <% end %>
  <br>
  <%= render :partial => "search_label" if @uploads_label.present? %>
</div>

<%= render :partial => "breadcrumbs" %>
<%= form_tag 'home/share/delete' do %>
<div class="asset_list_header">
  <div class="chk_box"> </div>
  <div class="file_name_header">File Name</div>
  <div class="file_size_header">Size</div>
  <div class="file_last_updated_header">Modified</div>
  <!-- <div class="file_last_updated_header">Delete</div> -->
  <p><%= submit_tag "Delete" %></p>
  <div class="file_last_updated_header">Actions</div>
</div>

<div class="asset_list">
  <% @being_shared_folders.each do |folder| %>
    <div class="asset_details <%= folder.shared? ? 'shared_folder' : 'folder' %>" id="folder_<%= folder.id %>">
        <div> </div>
        <div class="file_name"><%= link_to folder.name, browse_path(folder) %></div>
        <div class="file_size">-</div>
        <div class="file_last_updated">-</div>
        <div class="actions">
        </div>
    </div>
  <% end %>
  <!-- Listing Folders -->

  <% @folders.each do |folder| %>
  <div class="asset_details <%= folder.shared? ? 'shared_folder' : 'folder' %>" id="folder_<%= folder.id %>">
    <div class="file_name"><%= link_to folder.name, browse_path(folder) %></div>
    <div class="file_size">-</div>
    <div class="file_last_updated">-</div>
    <div class="actions">
    <div class="share">
        <%= link_to "Share", "#", :folder_id => folder.id, :folder_name => folder.name unless @is_this_folder_being_shared%>
    </div>
    <div class="rename">
        <%= link_to "Rename", url_for(:back) unless @is_this_folder_being_shared%>
    </div>
    <div class="delete">
        <%= link_to "Delete", folder,:data => { :confirm => 'Are you sure to delete the folder and all of its contents?'}, :method => :delete unless @is_this_folder_being_shared%>
    </div>
</div>
  </div>
  <% end %>

  <!-- Listing Files -->
  <% @uploads.each do |asset| %>
       <div class="asset_details file">
        <%= check_box_tag("file_ids[]", "#{asset.id}")%>
       <div class="file_name"><%= link_to asset.file_name, upload_path(asset) %></div>
       <div class="file_size"><%= number_to_human_size(asset.file_size, :precision => 2) %></div>
       <div class="file_last_updated"><%= asset.uploaded_file_updated_at %></div>
       <div class="actions">
           <!-- <div class="download">
               <%= link_to "Download", download_url(asset) %>
           </div> -->
           <div class="delete">
                <%= link_to "Delete", asset,:data => { :confirm => 'Are you sure?'}, :method => :delete unless @is_this_folder_being_shared%>
           </div>
       </div>
   </div>
<% end %>
<%end%>

<div id="invitation_form" title="Invite others to share" style="display:none" >
    <%= form_tag '/home/share' do%>
            <label for="email_addresses">Enter recipient email addresses here</label><br />
            <%= text_field_tag 'email_addresses', ""%>
            <br /><br />
            <label for="message">Optional message</label><br />
            <%= text_area_tag 'message',""%>
            <%= hidden_field_tag "folder_id" %>
    <% end -%>
</div>
</div>
<% end %>

app/views/home/share.js.erb
// the dialog box
$("#invitation_form").dialog("close");
$("#flash_notice").remove();
$("#container").prepend("<div id='flash_notice'>Successfully shared the folder</div>");
$("#folder_<%= params[:folder_id] %>").removeClass("folder");
$("#folder_<%= params[:folder_id] %>").addClass("shared_folder");