config/routes.rb
Rails.application.routes.draw do

 resources :folders
 resources :uploads
 devise_for :users
 root :to => "home#index"
 match "uploads/get/:id" => "uploads#get", :as => "download", via: [:get]
 match "browse/:folder_id" => "home#browse", :as => "browse", via: [:get, :post]
 match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder" , via: [:get,:post]
 match "browse/:folder_id/new_file" => "uploads#new", :as => "new_sub_file" , via: [:get,:post]
 match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder", via: [:get,:post]
 match "home/share" => "home#share", via: [:get,:post]
 match ":browse/:id/share/delete" => "uploads#bulk_delete", via: [:get,:post]
 match ":browse/home/label_search" => "uploads#label_search", via: [:get,:post]
 match "/home/label_search" => "uploads#label_search", via: [:get,:post]
 match "home/activity_data" => "home#activity_data",:as => "activity", via: [:get,:post]
 # match "/home/activity_data" => "home#activity_data",:as => "activity", via: [:get,:post]

 resources :uploads do
    resources :comments
  end

  resources 'surveys'
  resources 'attempts'
  delete 'attempts/:survey_id/:user_id' => 'attempts#delete_user_attempts', as: :delete_user_attempts
  post 'user/:id/change_name' => 'users#change_name', as: :change_user_name

  
  resources :comments do
    resources :comments
  end
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :folder, optional: true
  has_many :comments, as: :commentable

  audited associated_with: :user
  has_associated_audits

  has_attached_file :uploaded_file,
               :path => "assets/:id/:basename.:extension"

  validates_attachment_size :uploaded_file, :less_than => 10.megabytes
  validates_attachment_presence :uploaded_file
  validates_attachment_content_type :uploaded_file, :content_type => /^image\/(jpg|png)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'

  belongs_to :folder

  # validates_attachment_content_type :uploaded_file, :content_type => ["image/jpg", "image/png"]
  def file_name
    uploaded_file_file_name
  end

  def file_size
    uploaded_file_file_size
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_upload, only: [:show, :edit, :update, :destroy, :get]
  skip_before_filter :verify_authenticity_token, :only => [:label_search]

  def index
    @uploads = current_user.uploads
  end

  def show
    @upload = current_user.uploads.find(params[:id])
  end

  def label_search
    @uploads = current_user.uploads.where("label IN ('#{params["label_names"].join("','")}') ").order("uploaded_file_file_name desc")
  end

  def bulk_delete
    if params["file_ids"].present?
      params["file_ids"].each do |id|
        (Upload.find_by_id(id)).destroy
      end
    end
    redirect_to root_url
  end


  def new
    @upload = current_user.uploads.build
    if params[:folder_id]
      @current_folder = current_user.folders.find(params[:folder_id])
      @upload.folder_id = @current_folder.id
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = current_user.uploads.find(params[:id])
  end


  def get
    upload = current_user.uploads.find_by_id(params[:id])
    upload ||= Upload.find(params[:id]) if current_user.has_share_access?(Upload.find_by_id(params[:id]).folder)
    if upload
      #Parse the URL for special characters first before downloading
      # data = open(URI.parse(URI.encode(upload.uploaded_file.url)).to_s)

      #then again, use the "send_data" method to send the above binary "data" as file.
      # send_data data, :filename => upload.uploaded_file_file_name

      #redirect to amazon S3 url which will let the user download the file automatically
      redirect_to upload.uploaded_file.url, :type => upload.uploaded_file_content_type
    else
      flash[:error] = "Unauthorized Access!!"
      redirect_to root_url
    end
  end


  # POST /uploads
  # POST /uploads.json
  def create
    @upload = current_user.uploads.build(upload_params)
    if @upload.save
      flash[:notice] = "Successfully uploaded the file."
      if @upload.folder
        redirect_to browse_path(@upload.folder)
      else
        redirect_to root_url
      end
    else
      render :action => 'new'
    end
  end

  def update
    @upload = current_user.uploads.find(params[:id])
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @upload = current_user.uploads.find(params[:id])
    @parent_folder = @upload.folder
    @upload.destroy
    flash[:notice] = "Successfully deleted the file."
    if @parent_folder
     redirect_to browse_path(@parent_folder)
    else
     redirect_to root_url
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_upload
    @upload = Upload.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def upload_params
    params.require(:upload).permit(:uploaded_file, :user_id, :folder_id,:label)
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= form_for(upload) do |f| %>
<% if upload.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

  <ul>
    <% upload.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<p>
  <%= f.label :uploaded_file, "File" %><br />
  <%= f.file_field :uploaded_file %>
</p>
<p>
  <%= f.label :uploaded_file, "File label" %><br />
  <%= f.text_field :label %>
</p>

</p>
   <%= f.hidden_field :folder_id %>
<p>
<p><%= f.submit "Upload" %></p>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploads</h1>

<table>
  <thead>
    <tr>
    <th>Uploaded Files</th>
  </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= link_to upload.uploaded_file_file_name, upload.uploaded_file.url %></td>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/label_search.html.erb
<div class="asset_list_header">
  <div class="chk_box"> </div>
  <div class="file_name_header">File Name</div>
  <div class="file_size_header">Size</div>
  <div class="file_last_updated_header">Modified</div>
  <p><%= submit_tag "Delete" %></p>
  <div class="file_last_updated_header">Actions</div>
</div>
<% @uploads.each do |asset| %>
     <div class="asset_details file">
       <div class="file_name"><%= link_to asset.file_name, upload_path(asset) %></div>
       <div class="file_size"><%= number_to_human_size(asset.file_size, :precision => 2) %></div>
       <div class="file_last_updated"><%= asset.uploaded_file_updated_at %></div>
       <div class="actions">
           <div class="delete">
                <%= link_to "Delete", asset,:data => { :confirm => 'Are you sure?'}, :method => :delete unless @is_this_folder_being_shared%>
           </div>
       </div>
     </div>
<% end %>
<%= link_to 'Back', url_for(:back) %>

app/views/uploads/new.html.erb
<h1>Upload a file</h1>
<%= render :partial => "home/breadcrumbs" %>
<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Create File</button>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New File</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', upload: @upload %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>


<p>
<% if @upload.folder %>
   <%= link_to "Back to '#{@upload.folder.name}' Folder", browse_path(@upload.folder) %>
<% else %>
   <%= link_to "Back", root_url %>
<% end %>
</p>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>
<!-- <div class="row">
<div class="col-md-6"><span class="pull-left"></span></div>
</div> -->

<div class="container">
  <div class="row">
    <div class="pull-left">
      <%= image_tag @upload.uploaded_file.url, :class=>"img-responsive"%>
    </div>
    <div class="pull-right">
      <h3>Comments</h3>

      <%= form_for [@upload, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a comment" %><br/>
      <%= f.submit "Add Comment" %>
      <% end %>

      <ul>
        <%= render(partial: 'comments/comment', collection: @upload.comments) %>
      </ul>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= link_to 'Edit', edit_upload_path(@upload) %> |
    <%= link_to 'Back', uploads_path %>
  </div>
</div>